---

- include: install.yml
  when: nodejs_enabled
  tags: 
    - "nodejs"

- include: run_app.yml
  when: nodejs_enabled and nodejs_index is defined
  tags: 
    - "nodejs"

- include: logrotate.yml
  when: nodejs_enabled and nodejs_index is defined
  tags: 
    - "nodejs"
    - "logs"
    - "logrotate"
